### ISSUE TITLE
Error loading mods

### ISSUE THREAD

**Issue by stucker9** [spiwn/Fluid_Permutations#1]
http://prntscr.com/mya7ar

**Comment by stucker9** [comment]
https://pastebin.com/gj5yXkm1 for the current.log

**Comment by spiwn** [comment]
Thanks for the error report.
I see the problem. I will attempt to fix it as soon as possible.
It is happening because mods are adding a large variety of recipes in different 'shapes'. And my code has failed to handle all the 'shapes'. But I am happy to see mods doing this :)

**Comment by stucker9** [comment]
Hehe I'm happy to hear I could help. Thank you for your mod submission and pending fix!

**Comment by spiwn** [comment]
The 0.1.0 update should fix this problem. If it doesn't I have improved the error logging.

**Comment by stucker9** [comment]
Your fix has worked, thank you!

**Comment by stucker9** [comment]
Ah, I switched up my mod list to my Pyanodons loadout and got this on start up: https://pastebin.com/8ErTqzMi

**Comment by spiwn** [comment]
Alright, I see the problem:
``` Lua
  normal = {
    enabled = false,
    energy_required = 20,
    ingredients = {
      nil, --This here
      {
        "copper-plate",
        20
      },
```

I will update the mod, in a bit.

**Comment by spiwn** [comment]
New version is out. But I do not have time to properly test it.

**Comment by stucker9** [comment]
Problem fixed, thanks, nice job. Have a good day.
